---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-default
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  csi.storage.k8s.io/fstype: ext4
  type: gp3
  encrypted: "true"
  kmsKeyId: "4ecba96e-d3a2-4389-aac7-6f8320d3c5e6"
reclaimPolicy: Delete
allowVolumeExpansion: true